services:
  db:
    image: postgres:16
    container_name: spotwhere_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: spotwhere
      POSTGRES_PASSWORD: spotwhere_pass
      POSTGRES_DB: spotwhere
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
